### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by I-codebyte**
withdrawlimit added and transfer between to account

### CODE REVIEW

**Comment by joshuaunity** [comment]
hi, good evening. For the transfer feature you are not tracking the transaction into to transaction history. Transfers are also transactions so they must be tracked and added to your transaction history

**Comment by joshuaunity** [comment]
Your implementation of the daily withdrawal limit is not accurate, you are to check how much the user has withdraw for the day in question and then use that to determine if he/she has reached the limit

**Comment by I-codebyte** [comment]
I will do that once I have power on my pc. 
Thanks sir

**Comment by joshuaunity** [comment]
> I will do that once I have power on my pc. Thanks sir

Alright pleas submit before wednesday

**Comment by I-codebyte** [comment]
> > I will do that once I have power on my pc. Thanks sir
> 
> Alright pleas submit before wednesday

I've done it

**Comment by joshuaunity** [comment]
> > > I will do that once I have power on my pc. Thanks sir
> > 
> > 
> > Alright pleas submit before wednesday
> 
> I've done it

I checked, but unfortunately you didn't get the implementation of the  getTransactions feature

**Comment by joshuaunity** [comment]
I have done a correction section in the latest class for this assignment since many people didn't get this particular one, that way we all can see how it can be implemented. 

But I have acknowledge you 3rd assignment and will be merging this.

i look for ward to your 4th assignment, well-done 👍🏾

**Comment by I-codebyte** [comment]
> I have done a correction section in the latest class for this assignment since many people didn't get this particular one, that way we all can see how it can be implemented. 
> 
> But I have acknowledge you 3rd assignment and will be merging this.
> 
> i look for ward to your 4th assignment, well-done 👍🏾
> 
> 

Alright sir. Thanks

**Pull request merged**
